python_exam/apps/products/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^dashboard$', views.index, name='products_index'),
    url(r'^create$', views.create, name='products_create'),
    url(r'^wish_items/create$', views.createpage, name='products_createpage'),
    url(r'^wish_items/(?P<id>\d+)$', views.wishpage, name='products_wishpage'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='products_delete'),
    url(r'^wishadd/(?P<id>\d+)$', views.wishadd, name='wish_add'),
]

python_exam/apps/regandlogin/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='rnl_index'),
    url(r'^register$', views.register, name='rnl_register'),
    url(r'^login$', views.login, name='rnl_login'),
    url(r'^logout$', views.logout, name='rnl_logout'),
]

python_exam/main/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.regandlogin.urls', namespace = 'rnl')),
    url(r'^', include('apps.products.urls', namespace = 'products'))
]

python_exam/apps/products/models.py
from __future__ import unicode_literals
from ..regandlogin.models import User
from django.db import models

# Create your models here.

class ProductManager(models.Manager):
    def validate_product(self, form_data):
        errors = []
        user = Product.objects.filter(name = form_data['product'])
        if len(form_data['product']) == 0:
            errors.append('Item can not be blank!')
        if len(form_data['product']) <= 3:
            errors.append('Item has be over 3 characters!')
        return errors

class Product(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('regandlogin.User', related_name='user__product', null = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

python_exam/apps/regandlogin/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, re

name_regex = re.compile(r'^[a-zA-Z_ ]+$')

# Create your models here.

class UserManager(models.Manager):
    def validate_registration(self, form_data):
        errors = []
        user = User.objects.filter(username = form_data['username'])
        if len(form_data['name']) == 0:
            errors.append('Name is required!')
        if len(form_data['name']) < 3:
            errors.append('Name has be over 3 characters!')
        elif not name_regex.match(form_data['name']):
            errors.append('Your name has to be letters')

        if len(form_data['username']) == 0:
            errors.append('Username is required!')
        if len(form_data['username']) < 3:
            errors.append('Username has to be over 3 characters!')
        elif not name_regex.match(form_data['username']):
            errors.append('Username has to be letters')
        elif len(user) > 0:
            errors.append('This username already exist in the system!')

        if len(form_data['password']) == 0:
            errors.append('Password is required!')
        elif len(form_data['password']) < 8:
            errors.append('Your password cannot be less than 8 characters!')

        if len(form_data['conpassword']) == 0:
            errors.append('Password Confirmation is required!')
        elif form_data['conpassword'] != form_data['password']:
            errors.append('Your password fields do not match!')

        return errors

    def register(self, form_data):
        hashed_pass = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
        return self.create(name=form_data['name'], username=form_data['username'], password=hashed_pass)

    def check_login(self, form_data):
        check_user = self.filter(username=form_data['username'])
        if check_user:
            user = check_user[0]
            if bcrypt.hashpw(form_data['password'].encode(), user.password.encode()) == user.password:
                return user
        return None
    def logout(self):
        pass

class User(models.Model):
    name = models.CharField(max_length=40)
    username = models.CharField(max_length=40)
    password = models.CharField(max_length=255)
    wish = models.ManyToManyField('products.Product', related_name='user__wish')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

python_exam/apps/products/views.py
from django.shortcuts import render, redirect
from .models import Product
from ..regandlogin.models import User
from django.contrib import messages
# Create your views here.
def index(request):
    context ={
        'products': Product.objects.all(),
    }
    return render(request, 'products/index.html', context)

def createpage(request):
    return render(request, 'products/create.html')

def create(request):
    if request.method == 'POST':
        errors = Product.objects.validate_product(request.POST)
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('products:products_createpage')
        else:
            userobj = User.objects.get(id = request.session['user'])
            new_product = Product.objects.create(name = request.POST['product'], user = userobj)
            new_product.save()
            print new_product.user.name
    return redirect('products:products_index')

def delete(request, id):
    if request.method== 'GET':
        product_delete = Product.objects.get(id=id)
        product_delete.delete()
        return redirect('products:products_index')

def wishpage(request, id):
    context = {
        'items': Product.objects.filter(id = id)
    }
    return render(request, 'products/wishitems.html', context)

def wishadd(request, id):
    Product.objects.filter(id=id)
    user = User.objects.get(id=request.session['user'])
    product = Product.objects.get(id=id)
    user.wish.add(product)
    user.save()
    print User.wish.id
    return redirect('products:products:index')

python_exam/apps/regandlogin/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    return render(request, 'regandlogin/index.html')

def register(request):
    if request.method == 'POST':
        print 'yes'
        errors = User.objects.validate_registration(request.POST)
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('rnl:rnl_index')
        else:
            if User.objects.register(request.POST):
                messages.success(request, 'You have successfully created an account, please login to continue')
            else:
                messages.error(request, 'Something went wrong')
    return redirect(reverse('rnl:rnl_index'))

def login(request):
    if request.method != 'POST':
        return redirect('rnl:rnl_index')
    user = User.objects.check_login(request.POST)
    if user:
        request.session['user'] = user.id
        request.session['name'] = user.name
        print 'hello'
        return redirect('products:products_index')
    else:
        messages.error(request, 'Invalid login credentials')
        return redirect(reverse('rnl:rnl_index'))

def logout(request):
    request.session.pop('user')
    messages.success(request, 'Successful logged out')
    return redirect(reverse('rnl:rnl_index'))

python_exam/apps/products/templates/products/create.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Create Item</title>
    </head>
    <body>
        <div class="container">
            <header>
                <h1>Create a New Wish List Item</h1>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <a href="{% url 'products:products_index' %}">Home</a>
                <a href="{% url 'rnl:rnl_logout' %}">Logout</a>
            </header>
            <form action="{% url 'products:products_create' %}" method="POST">
                {% csrf_token %}
                Item/Product: <input type="text" name="product">
                <input type="submit" value="Add">
            </form>

        </div>
    </body>
</html>

python_exam/apps/products/templates/products/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Dashboard</title>
        {% load staticfiles  %}
        <link rel="stylesheet" href="{% static 'products/css/styles2.css' %}">
    </head>
    <body>
    <div class="container">
        <h1>Hello, {{request.session.name}}</h1>
        <a href="{% url 'products:products_index' %}">Home</a>
        <a href="{% url 'rnl:rnl_logout' %}">Logout</a>
        <div class="Yourwish">
            <h1>Your Wish List:</h1>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                {% for product in products %}
                {% if product.user.id == request.session.user %}
                <tr>
                    <td><a href="{% url 'products:products_wishpage' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.user.name}}</td>
                    <td>{{product.created_at}}</td>
                    {% if product.user.id == request.session.user %}
                    <td><a href="{% url 'products:products_delete' id=product.id %}">Delete</a></td>
                    {% endif %}
                    {% if product.user.id != request.session.user %}
                    <td><a href="{% url 'products:wish_add' id=product.id %}">Add to my wishlist</a></td>
                    {% endif %}
                {% endif %}

                </tr>
                {% endfor %}

            </table>
        </div>
        <div class="Otherwish">
            <h2>Other people wish list:</h2>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added By</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
                {% for product in products %}
                {% if product.user.id != request.session.user %}
                <tr class= 'wishitems'>
                    <td><a href="{% url 'products:products_wishpage' id=product.id %}">{{product.name}}</a></td>
                    <td>{{product.user.name}}</td>
                    <td>{{product.created_at}}</td>
                    <td><a href="{% url 'products:wish_add' id=product.id %}">Add to my wishlist</a></td>
                </tr>
                {% endif %}
                {% endfor %}
            </table>

        </div>
        <a href="{% url 'products:products_createpage' %}">Add Item</a>
    </div>
    </body>
</html>

python_exam/apps/products/templates/products/wishitems.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Wish Items</title>
    </head>
    <body>
        <div class="container">
            <header>
                <a href="{% url 'products:products_index' %}">Home</a>
                <a href="{% url 'rnl:rnl_logout' %}">Logout</a>
                {% for item in items %}
                <h1>Item Name: {{item.name}}</h1>
                <p>User who added this product: {{item.user.name}}</p>
                {% endfor %}
            </header>
        </div>
    </body>
</html>

python_exam/apps/regandlogin/templates/regandlogin/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Register and login</title>
        {% load staticfiles  %}
        <link rel="stylesheet" href="{% static 'regandlogin/css/styles.css' %}">
    </head>
    <body>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="register">
            <form action="{% url 'rnl:rnl_register' %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <legend>Register</legend>
                        <label>
                            Name:
                            <input type="text" name="name">
                        </label>
                        <label>
                            username:
                            <input type="text" name="username">
                        </label>
                        <label>
                            Password:
                            <input type="password" name="password">
                        </label>
                        <label>
                            Confirm Password:
                            <input type="password" name="conpassword">
                        </label>
                        <input type="submit" value="Register">
                </fieldset>
            </form>
        </div>
        <div class="login">
            <form action="/login" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Login</legend>
                        <label>
                            username:
                            <input type="text" name="username">
                        </label>
                        <label>
                            Password:
                            <input type="password" name="password">
                        </label>
                        <input type="submit" value="Login">
                </fieldset>
            </form>
        </div>
    </body>
</html>